export const CREATE_STORE_REQUEST = "CREATE_STORE_REQUEST";
export const CREATE_STORE_SUCCESS = "CREATE_STORE_SUCCESS";
export const CREATE_STORE_FAILURE = "CREATE_STORE_FAILURE";

export const GET_USER_STORE_REQUEST = "GET_USER_STORE_REQUEST";
export const GET_USER_STORE_SUCCESS = "GET_USER_STORE_SUCCESS";
export const GET_USER_STORE_FAILURE = "GET_USER_STORE_FAILURE";
