export const CREATE_SINGLE_ORDER_REQUEST = "CREATE_SINGLE_ORDER_REQUEST"
export const CREATE_SINGLE_ORDER_SUCCESS = "CREATE_SINGLE_ORDER_SUCCESS"
export const CREATE_SINGLE_ORDER_FAILURE = "CREATE_SINGLE_ORDER_FAILURE"

export const CREATE_CART_ORDER_REQUEST = "CREATE_CART_ORDER_REQUEST"
export const CREATE_CART_ORDER_SUCCESS = "CREATE_CART_ORDER_SUCCESS"
export const CREATE_CART_ORDER_FAILURE = "CREATE_CART_ORDER_FAILURE"

export const GET_USER_ORDER_REQUEST = "GET_USER_ORDER_REQUEST"
export const GET_USER_ORDER_SUCCESS = "GET_USER_ORDER_SUCCESS"
export const GET_USER_ORDER_FAILURE = "GET_USER_ORDER_FAILURE"

export const GET_ITEM_ORDER_REQUEST = "GET_ITEM_ORDER_REQUEST"
export const GET_ITEM_ORDER_SUCCESS = "GET_ITEM_ORDER_SUCCESS"
export const GET_ITEM_ORDER_FAILURE = "GET_ITEM_ORDER_FAILURE"

export const DELETE_ORDER_REQUEST = "DELETE_ORDER_REQUEST"
export const DELETE_ORDER_SUCCESS = "DELETE_ORDER_SUCCESS"
export const DELETE_ORDER_FAILURE = "DELETE_ORDER_FAILURE"