export const REGISTER_USER_REQUEST='REGISTER_USER_REQUEST';
export const REGISTER_USER_SUCCESS='REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILURE='REGISTER_USER_FAILURE';

export const LOGIN_USER_REQUEST='LOGIN_USER_REQUEST';
export const LOGIN_USER_SUCCESS='LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE='LOGIN_USER_FAILURE';

export const GET_USER_REQUEST='GET_USER_REQUEST';
export const GET_USER_SUCCESS='GET_USER_SUCCESS';
export const GET_USER_FAILURE='GET_USER_FAILURE';

export const UPLOAD_USER_PROFILE_REQUEST='UPLOAD_USER_PROFILE_REQUEST';
export const UPLOAD_USER_PROFILE_SUCCESS='UPLOAD_USER_PROFILE_SUCCESS';
export const UPLOAD_USER_PROFILE_FAILURE='UPLOAD_USER_PROFILE_FAILURE';

export const LOGOUT_REQUEST='LOGOUT_REQUEST';
export const LOGOUT_SUCCESS='LOGOUT_SUCCESS';
export const LOGOUT_FAILURE='LOGOUT_FAILURE';

export const ADD_TO_FAVORITES_REQUEST='ADD_TO_FAVORITES_REQUEST';
export const ADD_TO_FAVORITES_SUCCESS='ADD_TO_FAVORITES_SUCCESS';
export const ADD_TO_FAVORITES_FAILURE='ADD_TO_FAVORITES_FAILURE';

export const REMOVE_TO_FAVORITES_REQUEST='REMOVE_TO_FAVORITES_REQUEST';
export const REMOVE_TO_FAVORITES_SUCCESS='REMOVE_TO_FAVORITES_SUCCESS';
export const REMOVE_TO_FAVORITES_FAILURE='REMOVE_TO_FAVORITES_FAILURE';