export const GET_STORE_ORDER_REQUEST = "GET_STORE_ORDER_REQUEST"
export const GET_STORE_ORDER_SUCCESS = "GET_STORE_ORDER_SUCCESS"
export const GET_STORE_ORDER_FAILURE = "GET_STORE_ORDER_FAILURE"

export const UPDATE_STORE_ORDER_REQUEST = "UPDATE_STORE_ORDER_REQUEST"
export const UPDATE_STORE_ORDER_SUCCESS = "UPDATE_STORE_ORDER_SUCCESS"
export const UPDATE_STORE_ORDER_FAILURE = "UPDATE_STORE_ORDER_FAILURE"

